### ISSUE TITLE
Introduce N32 and N64 conventional names

### ISSUE THREAD

**Issue by LoZack19** [AndoniZubimendi/WinMIPS64#11]
https://github.com/AndoniZubimendi/WinMIPS64/blob/d1fd07fb4655d2d7d6b47f38f038210a50af301a/src/utils.cpp#L462

There are some other calling conventions which provide more arguments for function calling and I would really like to use them. Here is the list taken from wikipedia:

![image](https://github.com/user-attachments/assets/6fb12404-fb7a-48f2-b24f-10c79333add5)

**Comment by AndoniZubimendi** [comment]
From what I can see this alternative notation seems to add $a4-$a7 but remove $t0 - $t3. 

In our course we use a lot the temporary registers so this convention would not work well for us.

This project is based on a very old codebase and we are updating it slowly, so I do not think we can work on this feature now. 

I will close this issue now, but feel free to provide a pull request and we will reconsider it.
